var CouponStatusCodes = function(){};

CouponStatusCodes.REDEMPTION_LIMIT_EXCEEDED = 'REDEMPTION_LIMIT_EXCEEDED';
CouponStatusCodes.NO_ACTIVE_PROMOTION = 'NO_ACTIVE_PROMOTION';
CouponStatusCodes.COUPON_DISABLED = 'COUPON_DISABLED';
CouponStatusCodes.CUSTOMER_REDEMPTION_LIMIT_EXCEEDED = 'CUSTOMER_REDEMPTION_LIMIT_EXCEEDED';
CouponStatusCodes.NO_APPLICABLE_PROMOTION = 'NO_APPLICABLE_PROMOTION';
CouponStatusCodes.COUPON_CODE_ALREADY_REDEEMED = 'COUPON_CODE_ALREADY_REDEEMED';
CouponStatusCodes.COUPON_CODE_UNKNOWN = 'COUPON_CODE_UNKNOWN';
CouponStatusCodes.COUPON_CODE_ALREADY_IN_BASKET = 'COUPON_CODE_ALREADY_IN_BASKET';
CouponStatusCodes.TIMEFRAME_REDEMPTION_LIMIT_EXCEEDED = 'TIMEFRAME_REDEMPTION_LIMIT_EXCEEDED';
CouponStatusCodes.COUPON_ALREADY_IN_BASKET = 'COUPON_ALREADY_IN_BASKET';
CouponStatusCodes.APPLIED = 'APPLIED';


module.exports = CouponStatusCodes;