var HttpParameter = function(){};

HttpParameter.prototype.toString = function(){};
HttpParameter.prototype.getValue = function(){};
HttpParameter.prototype.isEmpty = function(){};
HttpParameter.prototype.getStringValue = function(){};
HttpParameter.prototype.getValues = function(){};
HttpParameter.prototype.getStringValues = function(){};
HttpParameter.prototype.containsStringValue = function(){};
HttpParameter.prototype.getBooleanValue = function(){};
HttpParameter.prototype.getIntValue = function(){};
HttpParameter.prototype.getDateValue = function(){};
HttpParameter.prototype.isChecked = function(){};
HttpParameter.prototype.isSubmitted = function(){};
HttpParameter.prototype.getDoubleValue = function(){};
HttpParameter.prototype.getRawValue = function(){};
HttpParameter.prototype.getRawValues = function(){};
HttpParameter.prototype.value=null;
HttpParameter.prototype.stringValue=null;
HttpParameter.prototype.values=null;
HttpParameter.prototype.stringValues=null;
HttpParameter.prototype.booleanValue=null;
HttpParameter.prototype.intValue=null;
HttpParameter.prototype.dateValue=null;
HttpParameter.prototype.doubleValue=null;
HttpParameter.prototype.rawValue=null;
HttpParameter.prototype.rawValues=null;

module.exports = HttpParameter;